### ISSUE TITLE
How can I apply it to the website?

### ISSUE THREAD

**Issue by ghostoact** [Querijn/LeagueModel#10]
I am interested in this. XD

**Comment by Querijn** [comment]
Hey there! Don't know what your website is, but I'm working on some documentation so that you can load this right up. Can I know where you want to put this?

In the meantime, here's my latest build, which is on https://irule.at/models right now: [Download](https://github.com/Querijn/LeagueModel/files/2714237/web.zip)

To make this work, you'll need to put the extracted game files into `data/output`. I cannot supply these files because it's quite a bit of files!

**Comment by ghostoact** [comment]
Thank you for your work.  It's so exciting. XD XD XD XD XD
