### ISSUE TITLE
A question about installation

### ISSUE THREAD

**Issue by RevyaM** [Querijn/LeagueModel#20]
Probably a stupid question, but I'm not sure where to put extracted files from league or if I have to set them up. 
I've tried setting up similar file architecture League uses and honestly, putting Ashe folder into every possible place. Not showing up in the menu, not sure if I have to write the file paths anywhere either.

**Comment by Querijn** [comment]
Hey, I haven't touched this in a while! I know the league file formats have changed quite a bit these few years, so I'll have a look to see if I can fix it this weekend.

**Comment by RevyaM** [comment]
> Hey, I haven't touched this in a while! I know the league file formats have changed quite a bit these few years, so I'll have a look to see if I can fix it this weekend.

Well, I was slightly skeptical that I'll get an answer honestly, so no matter the result, I appreciate it a lot!
Given that mindcorp can become quite a bit messy and doesn't support unorthodox texture formats (which can come with custom skins from time to time) I was searching for an alternative and stumbled upon this. 
I did try with Ashe model from S13 league, S2, S4 (I think?) and unorthodox dds (512x1024 etc) custom skins, and given that it ignores them all (not showing up in the selection menu)- I'm skeptical that I'm putting extracted files into the proper folders... or if it just that easy and if I need to write the path to model/dds somewhere.

**Comment by Querijn** [comment]
Hey, mine doesn't support custom skins either, was basically made to view original files. I do support some dds files natively on Windows.

**Comment by RevyaM** [comment]
> Hey, mine doesn't support custom skins either, was basically made to view original files. I do support some dds files natively on Windows.

Well, I was just trying to use every type I could, ranging from old S2 files to the modern S13, on top of trying to run those custom ones. I'm just not sure if I'm installing them properly, given that I'm putting Ashe folders in each and every place lol

**Comment by xcibe95x** [comment]
Hey i'm trying to use the codebase aswell, however i managed to get to the point where i get the list of champions and placed the file correctly after taking a look at the source code
But no matter what on web server or windows i get the gray background and when i load aatrox it output some logs but nothing shows up, do you think riot has changed their skin files again?
I extracted them and seems nothing changed externally, but however i can't say, i never fiddled with new rito files so far.
I was searching for a suitable solution for a project i'm working on and this is the only open source repo i found that had support to the new file formats
I'll try to play with it a little more and see if i can get any output.
If you might point me in the right direction to get the models to atleast display i would appreciate it, or even if you know any up to date open source model viewer i can integrate
Great work however, it seems this would have been a perfect fit for my current project

Edit: After spending a day trying to revive the application, I ended up integrating three.js in my project which turned out easier and faster to get something running and display an aatrox model and will be also easier to mantain inside the project itself
If anyone is interested in fixing this however my c++ knowledge is restricted, but i believe the problem is the .bin files have changed structure and the reading functions needs a rework

**Comment by Querijn** [comment]
Didn't know there was this much ask for it, so let me get into it:

Yeah, the bin parser is very outdated, and the format has changed slightly. Luckily, I have a fairly up-to-date version in another repo, and with a bit of luck, I can get this up and running today. I want to reduce it back to a basic form, with some ImGui things to simplify the work.

**Comment by Querijn** [comment]
I've updated the viewer with some basic UI. It should work with the instructions given in the readme. Let me know if you have any issues.

**Comment by RevyaM** [comment]
Sorry for late reply, got a bit busy with exams. 
I did try putting a new exe file into League folder (alongside with LeagueClient.exe etc) but it doesn't seem to launch at all. No trace of an exe in task manager either.

**Comment by Querijn** [comment]
That's odd. Do you have a `%LOCALAPPDATA%/CrashDumps` folder? Check if it has a LeagueModel file. Could you send it to me?

Also, feel free to add me on Discord: `@querijn`

**Comment by RevyaM** [comment]
Yup, quite a few about LeagueModel.exe

**Comment by Querijn** [comment]
I'd like the latest one you have.

**Comment by RevyaM** [comment]
[LeagueModel.exe.23760.dmp](https://github.com/Querijn/LeagueModel/files/13786159/LeagueModel.exe.23760.dmp)

**Comment by Querijn** [comment]
Fixed in https://github.com/Querijn/LeagueModel/releases/tag/v0.10.1

**Comment by RevyaM** [comment]
![image](https://github.com/Querijn/LeagueModel/assets/40909979/50b017d2-8868-47f2-b613-7a9f5a516a9d)

Yup, seems to be working now!
